apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: install-cni
spec:
  selector:
    matchLabels:
      name: install-cni
  template:
    metadata:
      labels:
        name: install-cni  
    spec:
      tolerations:
      # these tolerations are to have the daemonset runnable on control plane nodes
      # remove them if your control plane nodes should not run pods
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule    
      volumes:
      - name: cni
        hostPath:
          path: /opt/cni/bin 
          type: Directory 
      initContainers:
      - name: install
        image: ghcr.io/hujun-open/installcni:latest
        command: ['sh', '-c', '/getcni.sh /opt/cni/bin']
        volumeMounts:
        - mountPath: /opt/cni/bin
          name: cni
      containers:
      - name: pause
        image: registry.k8s.io/pause:3.9